export const SET_MODAL = 'SET_MODAL'
export const CLEAR_MODAL = 'CLEAR_MODAL'

export const SET_WIDGET = 'SET_WIDGET'
export const CLEAR_WIDGET = 'CLEAR_WIDGET'

export const SET_USER = 'SET_USER'
export const DELETE_USER = 'DELETE_USER'
export const EDIT_USER = 'EDIT_USER'

export const ENABLE_LOADER = 'ACTIVATE_LOADER'
export const DISABLE_LOADER = 'DISABLE_LOADER'

export const SET_MESSAGES = 'SET_MESSAGES'
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES'

export const SET_CALENDAR = 'SET_CALENDAR'
export const ERROR_CALENDAR = 'ERROR_CALENDAR'
export const LOADING_CALENDAR = 'LOADING_CALENDAR'
export const UPDATE_CALENDAR_EVENT = 'UPDATE_CALENDAR_EVENT'

export const SEARCH_TASKS_BY_STRING = 'SEARCH_TASKS_BY_STRING'
export const ADD_NEW_TASK = 'ADD_NEW_TASK'
export const GET_ALL_TASKS = 'GET_ALL_TASKS'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_TASKS_BY_CATEGORY = 'GET_TASKS_BY_CATEGORY'

export const GET_CATEGORY_INFO = 'GET_CATEGORY_INFO'
export const GET_TASK_DETAIL_INFO = 'GET_TASK_DETAIL_INFO'
